name: CI Workflows

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
